name: Continuous Integration

on: push

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup Elm
        uses: justgook/setup-elm@1.2.0

      - name: Run tests
        run: elm-verify-examples --run-tests
